<?php
/*
  This module looks for <img> tags of the class 'image-left', 'image-right' or 'standalone-image'
  with a title attibute set.  It then places the <img> tag in a <div> with the width and class
  attributes set. A <div> tag of class "caption" is also added with the caption text obtained
  from the title.  It removes the class attribute from the <img> tag.
  <img> tags missing alt attributes are also marked with warning text to draw attention to 
   this fact.
  @info
  http://drupal.org/node/264932
  @author
  John Fletcher
  @contact
  http://drupal.org/user/236219/contact
*/

/**
* Display help and module information
* @param path which path of the site we're displaying help
* @param arg array that holds the current path as would be returned from arg() function
* @return help text for the path
*/
function _image_caption_filter_tips($filter, $format, $long = FALSE) {
  return '<p>' . t("Adds captions to images") . '</p>';
}

/**
 * Implements hook_filter_info().
 */
function image_caption_filter_filter_info() {
  $filters['filter_image_caption'] = array(
    'title' => t('Image caption filter'),
    'description' => t('Adds captions to images via a filter'),
    'process callback' => '_filter_image_caption_filter_process',
    'tips callback' => '_image_caption_filter_tips',
  );
 
  return $filters;
}

function _filter_image_caption_filter_process($text, $filter, $format, $langcode, $cache, $cache_id) {
  $text = preg_replace_callback('|(<img.*?>)|s', 'doImgTitles', $text);

  return $text;
}

//helper function to do the actual manipulation
function doImgTitles($matches) {
  $imgText = $matches[0];

  // Get the title out of the <img> tag.
  preg_match('/title=\"(.+?)\"/i', $imgText, $matches);
  $title = isset($matches[1]) ? $matches[1] :  '';

  // Get the width out of the <img> tag.
  preg_match('/width=\"(.+?)\"/i', $imgText, $matches);
  $width = isset($matches[1]) ? $matches[1] :  '';

  // Get class out of the <img> tag.
  preg_match('/class=\"(.+?)\"/i', $imgText, $matches);
  $class = isset($matches[1]) ? $matches[1] :  '';

  //Only insert the caption and modify the <img> tag if it is has a title attribute and is one of the classes we are interested in
  if (in_array($class, variable_get('image_caption_class', array('image-left', 'image-right', 'standalone-image'))) && ($title)) {
    $imgText = preg_replace('/class=\"(.+?)\"/i', '', $imgText);
    
    $capption = array(
      'img' => array(
        '#type' => 'markup',
        '#markup' => $imgText,
      ),
      'caption' => array(
        '#theme' => 'container',
        '#attributes' => array(
          'class' => 'caption',
        ),
        '#children' => $title,
      ),
    );    
    
    $element = array(
      'image_caption' => array(
        '#theme' => 'container',
        '#attributes' => array(
          'class' => $class
        ),
        '#children' => render($caption),
      ),
    );

    return render($element);
  }
  return $imgText;
}
