<?php
/**
* @file
* $Id$
* Image Captioner Module using JQuery
* Requires javascript as enabled on client pc
* Adds a caption to images with 'caption' as their class using JQuery
* Caption is taken from image html title attribute
* @author David Thomas
* @contact davidwhthomas@gmail.com
*/

/**
* Implements hook_menu().
*/
function image_caption_menu() {
  $items = array();

  $items['admin/settings/image_caption'] = array(
    'title' => t('Image Caption Settings'),
    'description' => t('Configure image caption settings.'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('image_caption_admin_settings'),
    'access arguments' => array('administer site configuration')
  );

  return $items;
}

/*
* Implements the hook_admin_settings()
*/
function image_caption_admin_settings() {

  //node type settings
  $node_types = node_type_get_types();
  foreach ($node_types as $type) {
    $types[$type->type] = $type->name;
  }
  $form['image_caption_node_types'] = array(
    '#type' => 'select',
    '#title' => t('Select node types to include in image captioning'),
    '#default_value' => variable_get('image_caption_node_types', array()),
    '#multiple' => TRUE,
    '#options' => $types
  );
  return system_settings_form($form);
}

/*
* Implements hook_node_view()
* Add captioning javascript to page for certain node types
*/
function image_caption_node_view($node, $view_mode, $langcode) {
  if (in_array($node->type, variable_get('image_caption_node_types', array()))) {
    $path = drupal_get_path('module', 'image_caption');
    drupal_add_js($path.'/image_caption.js');
  }
}
